TEST: First open pull request, then apply labels

diff --git a/.github/workflows/alphachannel.yml b/.github/workflows/alphachannel.yml
--- a/.github/workflows/alphachannel.yml
+++ b/.github/workflows/alphachannel.yml
@@ -33,9 +33,35 @@ jobs:
 
         - name: Create Pull Request Using REST API
           run: |
+            # Make the request without labels. Export it to a file so we can add labels later
             curl \
+              -s \
               -X POST \
               -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository }}/pulls \
-              -d '{"title":"Merge ${{ github.ref }} into alpha","body":"Merge ${{ github.ref }} into alpha","head":"${{ github.ref }}","base":"alpha","labels":["auto-merge","auto-merge-squash"]}' || true
+              -d '{"title":"Merge ${{ github.ref }} into alpha","body":"Merge ${{ github.ref }} into alpha","head":"${{ github.ref }}","base":"alpha"}' \
+              -o pull_request.json
+            result=$?
+            if [ $result -ne 0 ]; then
+              echo "WARNING: curl failed with exit code $result"
+              exit 0
+            fi
+
+            # Add the labels to the pull request
+            issue_url=$(jq -r '.issue_url' pull_request.json)
+            echo "Adding labels to pull request $issue_url"
+            curl \
+              -s \
+              -X PUT \
+              -H "Accept: application/vnd.github.v3+json" \
+              -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
+              "$issue_url/labels" \
+              -d '["auto-merge","auto-merge-squash"]'
+
+        - name: Always upload artifacts
+          if: always()
+          uses: actions/upload-artifact@v2
+          with:
+            name: pull_request.json
+            path: pull_request.json
