TEST: Not using temporary branch

diff --git a/.github/workflows/mergeintoalpha.yml b/.github/workflows/mergeintoalpha.yml
--- a/.github/workflows/mergeintoalpha.yml
+++ b/.github/workflows/mergeintoalpha.yml
@@ -141,33 +141,33 @@ jobs:
               fi
             done
 
-        - name: Create temporary branch with random name
-          if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
-          run: |
-              git checkout -b temp-branch-${{ github.run_id }}
+        # - name: Create temporary branch with random name
+        #   if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
+        #   run: |
+        #       git checkout -b temp-branch-${{ github.run_id }}
 
-        - name: Push temporary branch
-          if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
-          run: |
-              git fetch
-              git config --global user.email "github-actions[bot]@users.noreply.github.com"
-              git config --global user.name "github-actions[bot]"
-              # git push origin temp-branch-${{ github.run_id }} --force || true
-              # push using github rest API
-              curl \
-                  -s \
-                  -X POST \
-                  -H "Accept: application/vnd.github.v3+json" \
-                  -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
-                  https://api.github.com/repos/${{ github.repository }}/git/refs \
-                  -d '{"ref":"refs/heads/temp-branch-'${{ github.run_id }}'","sha":"'${{ github.sha }}'"}'
-              # curl \
-              #     -s \
-              #     -X PATCH \
-              #     -H "Accept: application/vnd.github.v3+json" \
-              #     -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
-              #     https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
-              #     -d '{"head":"temp-branch-'${{ github.run_id }}'"}'
+        # - name: Push temporary branch
+        #   if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
+        #   run: |
+        #       git fetch
+        #       git config --global user.email "github-actions[bot]@users.noreply.github.com"
+        #       git config --global user.name "github-actions[bot]"
+        #       # git push origin temp-branch-${{ github.run_id }} --force || true
+        #       # push using github rest API
+        #       curl \
+        #           -s \
+        #           -X POST \
+        #           -H "Accept: application/vnd.github.v3+json" \
+        #           -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
+        #           https://api.github.com/repos/${{ github.repository }}/git/refs \
+        #           -d '{"ref":"refs/heads/temp-branch-'${{ github.run_id }}'","sha":"'${{ github.sha }}'"}'
+        #       # curl \
+        #       #     -s \
+        #       #     -X PATCH \
+        #       #     -H "Accept: application/vnd.github.v3+json" \
+        #       #     -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
+        #       #     https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
+        #       #     -d '{"head":"temp-branch-'${{ github.run_id }}'"}'
 
     push_to_base:
       runs-on: ubuntu-latest
@@ -189,8 +189,8 @@ jobs:
         - name: Fetch
           run: |
               git fetch
-              git checkout -b temp-branch-${{ github.run_id }} origin/temp-branch-${{ github.run_id }}
-              git pull
+              # git checkout -b temp-branch-${{ github.run_id }} origin/temp-branch-${{ github.run_id }}
+              # git pull
 
         - name: Create go tag with date
           id: date
@@ -229,21 +229,21 @@ jobs:
             git pull
             git config --global user.email "github-actions[bot]@users.noreply.github.com"
             git config --global user.name "github-actions[bot]"
-            git merge --no-edit temp-branch-${{ github.run_id }}
+            # git merge --no-edit temp-branch-${{ github.run_id }}
             # git push origin ${{ github.event.pull_request.base.ref }}
             # if head starts with temp-branch-, then push to base ref. Test with regex
-            if [[ "${{ github.event.pull_request.head.ref }}" =~ ^temp-branch-.* ]]; then
-              git push origin ${{ github.event.pull_request.base.ref }}
-            else
-              # merge the current PR using Rest API
-              curl \
-                  -s \
-                  -X PUT \
-                  -H "Accept: application/vnd.github.v3+json" \
-                  -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
-                  https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
-                  -d '{"commit_title":"Merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}","commit_message":"Merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}","sha":"'${{ github.sha }}'"}'
-            fi
+            # if [[ "${{ github.event.pull_request.head.ref }}" =~ ^temp-branch-.* ]]; then
+            #   git push origin ${{ github.event.pull_request.base.ref }}
+            # else
+            #   # merge the current PR using Rest API
+            curl \
+                -s \
+                -X PUT \
+                -H "Accept: application/vnd.github.v3+json" \
+                -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
+                https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
+                -d '{"commit_title":"Merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}","commit_message":"Merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}","sha":"'${{ github.sha }}'"}'
+            # fi
             # Get current commit hash
             commit_hash=$(git rev-parse HEAD)
             git checkout -b v-${{ steps.latest_tag.outputs.tag }}-alpha HEAD
@@ -312,26 +312,26 @@ jobs:
               curl -X POST -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" -H "Content-Type: application/json" -d '{"body": "This PR has not been merged into ${{ github.event.pull_request.base.ref }}. Please fix the issues and re-open the PR."}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
               curl -X PATCH -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" -H "Content-Type: application/json" -d '{"state": "closed"}' https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
 
-    cleanup_temp_branch:
-      runs-on: ubuntu-latest
-      timeout-minutes: 5
-      if: always() && contains(github.event.pull_request.labels.*.name, 'auto-merge')
-      needs: [run_tests, push_to_base]
-      steps:
-
-        - name: Checkout master
-          uses: actions/checkout@v3
-          with:
-            ref: master
-
-        - name: Delete temporary branch
-          run: |
-              git fetch
-              git checkout -b temp-branch-${{ github.run_id }} origin/temp-branch-${{ github.run_id }}
-              git pull
-              git checkout master
-              git branch -D temp-branch-${{ github.run_id }}
-              git push origin --delete temp-branch-${{ github.run_id }}
+    # cleanup_temp_branch:
+    #   runs-on: ubuntu-latest
+    #   timeout-minutes: 5
+    #   if: always() && contains(github.event.pull_request.labels.*.name, 'auto-merge')
+    #   needs: [run_tests, push_to_base]
+    #   steps:
+    #
+    #     - name: Checkout master
+    #       uses: actions/checkout@v3
+    #       with:
+    #         ref: master
+    #
+    #     - name: Delete temporary branch
+    #       run: |
+    #           git fetch
+    #           git checkout -b temp-branch-${{ github.run_id }} origin/temp-branch-${{ github.run_id }}
+    #           git pull
+    #           git checkout master
+    #           git branch -D temp-branch-${{ github.run_id }}
+    #           git push origin --delete temp-branch-${{ github.run_id }}
 
     cleanup_head_branch:
       runs-on: ubuntu-latest
