TEST: Check PR merge result

diff --git a/.github/workflows/mergeintoalpha.yml b/.github/workflows/mergeintoalpha.yml
--- a/.github/workflows/mergeintoalpha.yml
+++ b/.github/workflows/mergeintoalpha.yml
@@ -235,14 +235,24 @@ jobs:
             # if [[ "${{ github.event.pull_request.head.ref }}" =~ ^temp-branch-.* ]]; then
             #   git push origin ${{ github.event.pull_request.base.ref }}
             # else
-            #   # merge the current PR using Rest API
+            #   # merge the current PR using Rest API, check response, and if not ok, exit with error
             curl \
                 -s \
                 -X PUT \
                 -H "Accept: application/vnd.github.v3+json" \
                 -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
                 https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
-                -d '{"commit_title":"Merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}","commit_message":"Merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}","sha":"'${{ github.sha }}'"}'
+                -d '{"commit_title":"Merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}","commit_message":"Merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}","sha":"'${{ github.sha }}'","merge_method":"squash"}' \
+                -o merge_response.json
+            # parse merge_response.json message to check if merge was successful. Use jq
+            merge_response=$(cat merge_response.json)
+            echo "merge_response: $merge_response"
+            merge_response_message=$(echo $merge_response | jq -r '.message')
+            echo "merge_response_message: $merge_response_message"
+            if [ "$merge_response_message" != "Pull Request successfully merged" ]; then
+              echo "ERROR: Merge failed"
+              exit 1
+            fi
             # fi
             # Get current commit hash
             commit_hash=$(git rev-parse HEAD)
