UPDATE: Process failed tests

diff --git a/.github/workflows/mergeintoalpha.yml b/.github/workflows/mergeintoalpha.yml
--- a/.github/workflows/mergeintoalpha.yml
+++ b/.github/workflows/mergeintoalpha.yml
@@ -161,6 +161,20 @@ jobs:
               name: test_output.txt
               path: test_output.txt
 
+        - name: Process tests output
+          run: |
+            # Select from test_output.txt only lines containing "---FAIL: "
+            all_failed_tests=$(cat test_output.txt | grep "--- FAIL: ")
+            failed_tests=$(echo "$all_failed_tests" | wc -l)            
+            echo "failed_tests=$failed_tests" >> $GITHUB_OUTPUT
+            if [ $failed_tests -ne 0 ]; then
+              echo "Tests failed:"
+              echo $all_failed_tests
+              exit 1
+            else
+              echo "Tests passed"
+            fi
+
         - name: Process coverage.summary.txt
           run: |
             # Parse coverage_lines to get coverage percentage. If any percentage is below $MIN_COVERAGE_THRESHOLD, exit with error
