UPDATE: Internal changes in CI

diff --git a/.github/workflows/mergeintoalpha.yml b/.github/workflows/mergeintoalpha.yml
--- a/.github/workflows/mergeintoalpha.yml
+++ b/.github/workflows/mergeintoalpha.yml
@@ -1,9 +1,44 @@
 name: Accept PRs into alpha
+# Run only on last label
 on:
   pull_request:
-    types: [opened, synchronize, reopened, labeled]
+    types: [synchronize, reopened, labeled]
+concurrency:
+  group: ${{ github.event.pull_request.number }}
+  cancel-in-progress: false
 
 jobs:
+
+    check_pr:
+      runs-on: ubuntu-latest
+      env:
+        GITHUB_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
+      outputs:
+        pr_state: ${{ steps.check_pr_status.outputs.pr_state }}
+      steps:
+
+        - name: Check PR Status
+          id: check_pr_status
+          run: |
+            # Check if PR is open
+            curl \
+                -s \
+                -X GET \
+                -H "Accept: application/vnd.github.v3+json" \
+                -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
+                https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
+                -o pull_request.json
+            result=$?
+            if [ $result -ne 0 ]; then
+              echo "WARNING: curl failed with exit code $result"
+              exit 0
+            fi
+            pr_state=$(cat pull_request.json | jq -r '.state')
+            echo "PR state: $pr_state"
+            echo "pr_state=$pr_state" >> $GITHUB_OUTPUT
+            if [ "$pr_state" != "open" ]; then
+              echo "WARNING: PR is not open. Exiting"
+            fi 
 
     run_tests:
       runs-on: ubuntu-latest
@@ -146,24 +181,12 @@ jobs:
               fi
             done
 
-        - name: Create temporary branch with random name
-          if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
-          run: |
-              git checkout -b temp-branch-${{ github.run_id }}
 
-        - name: Push temporary branch
-          if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
-          run: |
-              git fetch
-              git config --global user.email "github-actions[bot]@users.noreply.github.com"
-              git config --global user.name "github-actions[bot]"
-              git push origin temp-branch-${{ github.run_id }} --force || true
-
-    push_to_base:
+    merge_pr:
       runs-on: ubuntu-latest
       timeout-minutes: 5
-      if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
-      needs: [run_tests]
+      if: needs.check_pr.outputs.pr_state == 'open' && contains(github.event.pull_request.labels.*.name, 'auto-merge')
+      needs: [check_pr, run_tests]
       env:
         GITHUB_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
       outputs:
@@ -179,8 +202,8 @@ jobs:
         - name: Fetch
           run: |
               git fetch
-              git checkout -b temp-branch-${{ github.run_id }} origin/temp-branch-${{ github.run_id }}
-              git pull
+              # git checkout -b temp-branch-${{ github.run_id }} origin/temp-branch-${{ github.run_id }}
+              # git pull
 
         - name: Create go tag with date
           id: date
@@ -211,36 +234,45 @@ jobs:
             # echo "::set-output name=tag::${new_tag}"
             echo "tag=${new_tag}" >> $GITHUB_OUTPUT
 
-        - name: Push
+        - name: Merge PR
           run: |
-            git fetch
-            # Push local temp branch to remote base branch
-            git checkout -b ${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.base.ref }}
-            git pull
-            git config --global user.email "github-actions[bot]@users.noreply.github.com"
-            git config --global user.name "github-actions[bot]"
-            git merge --no-edit temp-branch-${{ github.run_id }}
-            git push origin ${{ github.event.pull_request.base.ref }}
-            # Get current commit hash
-            commit_hash=$(git rev-parse HEAD)
-            git checkout -b v-${{ steps.latest_tag.outputs.tag }}-alpha HEAD
-            git branch --set-upstream-to=origin/v-${{ steps.latest_tag.outputs.tag }}-alpha v-${{ steps.latest_tag.outputs.tag }}-alpha || true
-            # git pull --rebase || true
-            # git merge --no-edit temp-branch-${{ github.run_id }}
-            git reset --hard $commit_hash
-            git push -f origin v-${{ steps.latest_tag.outputs.tag }}-alpha
+            curl \
+                -s \
+                -X PUT \
+                -H "Accept: application/vnd.github.v3+json" \
+                -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
+                https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
+                -d '{"commit_title":"Merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}","commit_message":"Merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}","merge_method":"merge"}' \
+                -o merge_response.json
+            # parse merge_response.json message to check if merge was successful. Use jq
+            merge_response=$(cat merge_response.json)
+            echo "merge_response: $merge_response"
+            merge_response_message=$(echo $merge_response | jq -r '.message')
+            echo "merge_response_message: $merge_response_message"
+            if [ "$merge_response_message" != "Pull Request successfully merged" ]; then
+              echo "ERROR: Merge failed"
+              exit 1
+            fi
+            merged_sha=$(echo $merge_response | jq -r '.sha')
+            curl \
+                -s \
+                -X PATCH \
+                -H "Accept: application/vnd.github.v3+json" \
+                -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
+                https://api.github.com/repos/${{ github.repository }}/git/refs/heads/v-${{ steps.latest_tag.outputs.tag }}-alpha \
+                -d '{"sha":"'$merged_sha'"}'
 
     close_pr_success:
       runs-on: ubuntu-latest
       timeout-minutes: 5
-      if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
-      needs: [run_tests, push_to_base]
+      if: needs.check_pr.outputs.pr_state == 'open' && contains(github.event.pull_request.labels.*.name, 'auto-merge')
+      needs: [run_tests, merge_pr]
       steps:
 
-        - name: Sets the pull request milestone using ${{ needs.push_to_base.outputs.tag }}
+        - name: Sets the pull request milestone using ${{ needs.merge_pr.outputs.tag }}
           run: |
             # First converts tag "x.y.z" to milestone "vx.y"
-            milestone_title=$(echo ${{ needs.push_to_base.outputs.tag }} | sed 's/\([0-9]*\.[0-9]*\)\.[0-9]*/v\1/')
+            milestone_title=$(echo ${{ needs.merge_pr.outputs.tag }} | sed 's/\([0-9]*\.[0-9]*\)\.[0-9]*/v\1/')
             echo "Milestone: $milestone_title"
             # List milestones to obtain milestone number
             curl -s -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/milestones > milestones.json
@@ -272,8 +304,8 @@ jobs:
       runs-on: ubuntu-latest
       timeout-minutes: 5
       # Only if the pull request has the label 'auto-merge' and does not have the label 'close-on-success' and has failed
-      if: always() && contains(github.event.pull_request.labels.*.name, 'auto-merge') && !contains(github.event.pull_request.labels.*.name, 'close-on-success') && contains(needs.*.result, 'failure')
-      needs: [run_tests, push_to_base]
+      if: always()&& needs.check_pr.outputs.pr_state == 'open' && contains(github.event.pull_request.labels.*.name, 'auto-merge') && !contains(github.event.pull_request.labels.*.name, 'close-on-success') && contains(needs.*.result, 'failure')
+      needs: [run_tests, merge_pr]
       steps:
 
         - name: Comments on the pull request and closes it
@@ -281,32 +313,12 @@ jobs:
               curl -X POST -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" -H "Content-Type: application/json" -d '{"body": "This PR has not been merged into ${{ github.event.pull_request.base.ref }}. Please fix the issues and re-open the PR."}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
               curl -X PATCH -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" -H "Content-Type: application/json" -d '{"state": "closed"}' https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
 
-    cleanup_temp_branch:
-      runs-on: ubuntu-latest
-      timeout-minutes: 5
-      if: always() && contains(github.event.pull_request.labels.*.name, 'auto-merge')
-      needs: [run_tests, push_to_base]
-      steps:
-
-        - name: Checkout master
-          uses: actions/checkout@v3
-          with:
-            ref: master
-
-        - name: Delete temporary branch
-          run: |
-              git fetch
-              git checkout -b temp-branch-${{ github.run_id }} origin/temp-branch-${{ github.run_id }}
-              git pull
-              git checkout master
-              git branch -D temp-branch-${{ github.run_id }}
-              git push origin --delete temp-branch-${{ github.run_id }}
 
     cleanup_head_branch:
       runs-on: ubuntu-latest
       timeout-minutes: 5
-      if: always() && contains(github.event.pull_request.labels.*.name, 'delete-branch') && !contains(github.event.pull_request.labels.*.name, 'close-on-success')
-      needs: [run_tests, push_to_base, close_pr_success, close_pr_failure]
+      if: always() && needs.check_pr.outputs.pr_state == 'open' && contains(github.event.pull_request.labels.*.name, 'delete-branch') && !contains(github.event.pull_request.labels.*.name, 'close-on-success')
+      needs: [run_tests, merge_pr, close_pr_success, close_pr_failure]
       steps:
 
         - name: Checkout master
