UPDATE: Internal changes in CI
- Check PR status

diff --git a/.github/workflows/mergeintoalpha.yml b/.github/workflows/mergeintoalpha.yml
--- a/.github/workflows/mergeintoalpha.yml
+++ b/.github/workflows/mergeintoalpha.yml
@@ -9,8 +9,42 @@ concurrency:
 
 jobs:
 
+    check_pr:
+      runs-on: ubuntu-latest
+      env:
+        GITHUB_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
+      outputs:
+        pr_state: ${{ steps.check_pr_status.outputs.pr_state }}
+      steps:
+
+        - name: Check PR Status
+          id: check_pr_status
+          run: |
+            # Check if PR is open
+            curl \
+                -s \
+                -X GET \
+                -H "Accept: application/vnd.github.v3+json" \
+                -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" \
+                https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
+                -o pull_request.json
+            result=$?
+            if [ $result -ne 0 ]; then
+              echo "WARNING: curl failed with exit code $result"
+              exit 0
+            fi
+            pr_state=$(cat pull_request.json | jq -r '.state')
+            echo "PR state: $pr_state"
+            echo "pr_state=$pr_state" >> $GITHUB_OUTPUT
+            if [ "$pr_state" != "open" ]; then
+              echo "WARNING: PR is not open. Exiting"
+            fi 
+
     run_tests:
       runs-on: ubuntu-latest
+      needs:
+        - check_pr
+      if: ${{ needs.check_pr.outputs.pr_state }} == 'open'
       timeout-minutes: 5
       strategy:
         matrix:
